all:
	@echo "make[1]: Entering directory '/workspace'"
	@echo "cc -O2 alpha.c"
	@echo ""
	@echo "cc -O2 beta.c"
	@echo "make[1]: Leaving directory '/workspace'"

silent:
	@echo "make[1]: Entering directory '/workspace'"
	@echo "make[1]: Leaving directory '/workspace'"

broken:
	@echo "make[1]: Entering directory '/workspace'"
	@exit 1
