use futures_util::future::join_all;
use url::Url;

use crate::budget::ResolutionBudget;
use crate::cache::CacheRead;
use crate::candidates::{FallbackCandidate, build_fallback_candidates};
use crate::icon_fetch::{
    FetchOutcome, FetchSpec, definitive_http_failure, normalized_content_type,
};
use crate::image_normalize::sniff_icon_kind;
use crate::resolver::{
    CacheCounts, ResolveSourceIconOptions, SourceIconCacheInfo, SourceIconError, SourceIconResolver,
};
use crate::resolver_options::url_is_within_limits;

impl SourceIconResolver {
    pub(crate) async fn resolve_fallback(
        &self,
        page_url: &Url,
        options: &ResolveSourceIconOptions,
        budget: &ResolutionBudget,
        cache: &mut SourceIconCacheInfo,
    ) -> Result<Option<Url>, SourceIconError> {
        let candidates = build_fallback_candidates(page_url, options.max_candidates);
        for batch in candidates.chunks(options.probe_batch_size) {
            // Batching caps fan-out while avoiding serial latency across the
            // common 404s generated by conventional favicon guesses.
            let results = join_all(
                batch
                    .iter()
                    .map(|candidate| self.probe_candidate(candidate, options, budget)),
            )
            .await;
            let mut winner = None;
            for result in results {
                let result = result?;
                cache.probe.hits += result.cache.hits;
                cache.probe.misses += result.cache.misses;
                cache.probe.writes += result.cache.writes;
                if winner.is_none() {
                    winner = result.url;
                }
            }
            if winner.is_some() {
                return Ok(winner);
            }
        }
        Ok(None)
    }

    async fn probe_candidate(
        &self,
        candidate: &FallbackCandidate,
        options: &ResolveSourceIconOptions,
        budget: &ResolutionBudget,
    ) -> Result<ProbeResult, SourceIconError> {
        let key = format!("{}\0probe={}", candidate.url, options.max_probe_bytes);
        match self.caches.get_probe(&key) {
            CacheRead::Hit(value) => {
                return Ok(ProbeResult {
                    url: value.and_then(|value| Url::parse(&value).ok()),
                    cache: CacheCounts {
                        hits: 1,
                        ..CacheCounts::default()
                    },
                });
            }
            CacheRead::Miss => {}
        }
        let range = format!("bytes=0-{}", options.max_probe_bytes - 1);
        let response = self
            .fetch(
                FetchSpec {
                    url: &candidate.url,
                    timeout: options.probe_timeout,
                    max_body_bytes: options.max_probe_bytes,
                    accept: "image/*,*/*;q=0.1",
                    range: Some(&range),
                },
                options,
                budget,
            )
            .await?;
        let (resolved, cacheable) = match response {
            FetchOutcome::Response(response) if response.status.is_success() => {
                let content_type = normalized_content_type(&response.headers).unwrap_or_default();
                let resolved = if (content_type.starts_with("image/")
                    && !content_type.contains("html"))
                    || sniff_icon_kind(&response.body).is_some()
                {
                    url_is_within_limits(&response.url).then_some(response.url)
                } else {
                    None
                };
                (resolved, true)
            }
            FetchOutcome::Response(response) => (None, definitive_http_failure(response.status)),
            FetchOutcome::DefinitiveFailure => (None, true),
            FetchOutcome::TransientFailure => (None, false),
        };
        if cacheable {
            self.caches
                .put_probe(key, resolved.as_ref().map(ToString::to_string));
        }
        Ok(ProbeResult {
            url: resolved,
            cache: CacheCounts {
                misses: 1,
                writes: usize::from(cacheable),
                ..CacheCounts::default()
            },
        })
    }
}

struct ProbeResult {
    url: Option<Url>,
    cache: CacheCounts,
}
